version: "3"
services:
    course-reviewer-test:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            ACCEPT_EULA: "Y"
            MSSQL_SA_PASSWORD: "YourStrong@Passw0rd"
        ports:
            - "1433:1433"
